### ISSUE TITLE
wget: unrecognized option `--no-check-certificate'

### ISSUE THREAD

**Issue by once375ml** [rehiy/dnspod-shell#89]
Router OS: FreshTomato Firmware 2021.7 K26ARM USB VPN-64K

反馈：wget: unrecognized option `--no-check-certificate'

说明有Wget，但是版本较老？无法支持 `--no-check-certificate'？

查阅FreshTomato Changelog，说有CA。
- libcurl: update CA certificate bundle as of 2021-09-30

注释掉：wget -q -O- --no-check-certificate -U $agent --post-data $params $apiurl
另写一行：wget -q -O- -U $agent --post-data $params $apiurl
反馈：wget: unrecognized option `--post-data'

下面不会了……

**Comment by rehiy** [comment]
可能是使用了busybox自带的wget导致的，需要使用独立的wget，或者busybox支持openssl的版本
&nbsp;

若海 https://www.rehiy.com


&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2021年11月21日(星期天) 晚上10:04
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: [rehiy/dnspod-shell] wget: unrecognized option `--no-check-certificate&#39; (Issue #89)





 
Router OS: FreshTomato Firmware 2021.7 K26ARM USB VPN-64K
 
反馈：wget: unrecognized option `--no-check-certificate'
 
说明有Wget，但是版本较老？无法支持 `--no-check-certificate'？
 
查阅FreshTomato Changelog，说有CA。
  
libcurl: update CA certificate bundle as of 2021-09-30
  
注释掉：
 
wget -q -O- --no-check-certificate -U $agent --post-data $params $apiurl
     wget -q -O- -U $agent --post-data $params $apiurl  
反馈：wget: unrecognized option `--post-data'
 
下面不会了……
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
